from Tkinter import *
import ttk
import tkFileDialog as tfd
from base import Base
from extraction import Extraction
class gui(Base):
    def __init__(self,window):
        window.title('new window')
        window.resizable(True,False)
        window.geometry('800x640+400+150')
        self.nb=ttk.Notebook(window,height=640,width=800)
        self.nb.pack()
        self.f1=ttk.Frame(self.nb,height=640,width=800,relief=SOLID)
        self.f2=ttk.Frame(self.nb,height=640,width=800,relief=SOLID)
        self.l1=ttk.Label(self.f1,text='Welcome !')
        self.l1.place(relx=0.5,rely=0,y=5)
        self.b1=ttk.Button(self.f1,text='select file',command=self.selfil)
        self.b1.place(relx=0.5,x=-100,y=70)
        self.nb.add(self.f1,text="main")
        self.nb.add(self.f2,text='Temperature range')
        self.nb.select(0)
        self.l3=Label(self.f1,text='filepath',wraplength=300)
        self.l3.place(relx=0.5,x=100,y=70)
        self.cb=ttk.Checkbutton(self.f1)
        self.cb2=ttk.Checkbutton(self.f1)
        self.cb3=ttk.Checkbutton(self.f1)
        self.cb4=ttk.Checkbutton(self.f1)
        self.cb5=ttk.Checkbutton(self.f1)
        self.cb6=ttk.Checkbutton(self.f1)
        self.evs=Entry(self.f1,width=25)
        self.evp=Entry(self.f1,width=25)
        self.h1=ttk.Label(self.f2,text='Temperature range for')
        self.h2=ttk.Label(self.f2,text='Forging',background='white')
        self.h3=ttk.Label(self.f2,text='Casting',background='white')
        self.v1=ttk.Label(self.f2,text='A105')
        self.v2=ttk.Label(self.f2,text='F22')
        self.v3=ttk.Label(self.f2,text='F91')
        self.v4=ttk.Label(self.f2,text='F92')
        self.v5=ttk.Label(self.f2,text='WCB')
        self.v6=ttk.Label(self.f2,text='WCC')
        self.v7=ttk.Label(self.f2,text='WC9')
        self.v8=ttk.Label(self.f2,text='C12A')
        self.v1=ttk.Label(self.f2,text='A105')
        self.v2=ttk.Label(self.f2,text='F22')
        self.v3=ttk.Label(self.f2,text='F91')
        self.v4=ttk.Label(self.f2,text='F92')
        self.v5=ttk.Label(self.f2,text='WCB')
        self.v6=ttk.Label(self.f2,text='WCC')
        self.v7=ttk.Label(self.f2,text='WC9')
        self.v8=ttk.Label(self.f2,text='C12A')
        a105=DoubleVar()
        f22=DoubleVar()
        f91=DoubleVar()
        f92=DoubleVar()
        wcb=DoubleVar()
        wcc=DoubleVar()
        wc9=DoubleVar()
        c12a=DoubleVar()
        c12ab=DoubleVar()
        self.ent1=Entry(self.f2,width=10,textvariable=a105)
        self.ent2=Entry(self.f2,width=10,textvariable=f22)
        self.ent3=Entry(self.f2,width=10,textvariable=f91)
        self.ent4=Entry(self.f2,width=10,textvariable=f92)
        self.ent5=Entry(self.f2,width=10,textvariable=wcb)
        self.ent6=Entry(self.f2,width=10,textvariable=wcc)
        self.ent7=Entry(self.f2,width=10,textvariable=wc9)
        self.ent8=Entry(self.f2,width=5,textvariable=c12a)
        self.ent9=Entry(self.f2,width=5,textvariable=c12ab)
        a105.set(400)
        f22.set(550)
        f91.set(601)
        f92.set(610)
        wcb.set(400)
        wcc.set(400)
        wc9.set(550)
        c12a.set(601)
        c12ab.set(610)
        self.op=ttk.Label(self.f1,text='Output')
        rating=StringVar()
        part_number=StringVar()
        material=StringVar()
        size=StringVar()
        part_number2=StringVar()
        self.cb.config(text='RATING EXTRACTION',variable=rating,onvalue='YES',offvalue='NO')
        self.cb2.config(text='ONLINE PART NUMBER FETCH(SERVER)',variable=part_number,onvalue='YES',offvalue='NO')
        self.cb3.config(text='MATERIAL CHECK',variable=material,onvalue='YES',offvalue='NO')
        self.cb4.config(text='INCHES',variable=size,onvalue='IN',offvalue='NO')
        self.cb5.config(text='NB',variable=size,onvalue='NB',offvalue='NO')
        self.cb6.config(text='OFFLINE PART NUMBER FETCH (EXCEL) ',variable=part_number2,onvalue='YES',offvalue='NO')
        self.l4=ttk.Label(self.f1,text="Select the actions to perform.",wraplength=200)
        self.l5=ttk.Label(self.f1,text="Select the final size format.",wraplength=200)
        self.pb=ttk.Progressbar(self.f1,orient=HORIZONTAL,length=450)
        self.start_b=ttk.Button(self.f1,text='Start',command= lambda :self.startt(self.fn,rating.get(),part_number.get(),part_number2.get(),material.get(),size.get(),a105.get(),f22.get(),f91.get(),f92.get(),wcb.get(),wcc.get(),wc9.get(),c12a.get(),c12ab.get()))
        self.l4.place(x=50,rely=0.5,y=-120)
        self.cb.place(x=50,rely=0.5,y=-100)
        self.cb2.place(x=50,rely=0.5,y=-80)
        self.cb3.place(x=50,rely=0.5,y=-60)
        self.cb6.place(x=50,rely=0.5,y=-40)
        self.cb4.place(relx=1,x=-200,rely=0.5,y=-100)
        self.cb5.place(relx=1,x=-200,rely=0.5,y=-80)
        self.l5.place(relx=1,x=-200,rely=0.5,y=-120)
        self.vs=ttk.Label(self.f1,text='VALVE SCHEDULE')
        self.vp=ttk.Label(self.f1,text='VALVE PROJECT')
        self.vp.place(relx=0.5,rely=0.5,x=-178,y=-200,anchor='nw')
        self.vs.place(relx=0.5,rely=0.5,x=200,y=-200,anchor='ne')
        self.evs.place(relx=0.5,rely=0.5,x=100,y=-175,anchor='nw')
        self.evp.place(relx=0.5,rely=0.5,x=-100,y=-175,anchor='n')
        self.start_b.place(relx=0.5,rely=0.5,y=-10)
        self.pb.place(relx=0.5,rely=0.5,x=45,y=50,anchor='center')
        self.h1.place(relx=0.5,y=10,anchor='n')
        self.h2.place(relx=0.5,x=-100,y=50,anchor='e')
        self.h3.place(relx=0.5,x=100,y=50,anchor='w')
        self.v1.place(relx=0.5,x=-170,y=80)
        self.ent1.place(relx=0.5,x=-120,y=80)
        self.v2.place(relx=0.5,x=-170,y=110)
        self.ent2.place(relx=0.5,x=-120,y=110)
        self.v3.place(relx=0.5,x=-170,y=140)
        self.ent3.place(relx=0.5,x=-120,y=140)
        self.v4.place(relx=0.5,x=-170,y=170)
        self.ent4.place(relx=0.5,x=-120,y=170)
        self.v5.place(relx=0.5,x=80,y=80)
        self.ent5.place(relx=0.5,x=130,y=80)
        self.v6.place(relx=0.5,x=80,y=110)
        self.ent6.place(relx=0.5,x=130,y=110)
        self.v7.place(relx=0.5,x=80,y=140)
        self.ent7.place(relx=0.5,x=130,y=140)
        self.v8.place(relx=0.5,x=80,y=170)
        self.ent8.place(relx=0.5,x=130,y=170)
        self.ent9.place(relx=0.5,x=170,y=170)
        self.term=Text(self.f1,width=50,height=5,wrap='word')
        self.term.place(relx=0.5,rely=0.5,y=180,x=50,anchor='center')
        self.op.place(relx=0.5,rely=0.5,y=100,x=-130,anchor='n')
    def selfil(self):
        self.fn=''
        filename=tfd.askopenfilename()
        self.fn=filename
        self.l3.config(text=filename)
        print filename
    def startt(self,fn,rating,part,part2,material,size,a105,f22,f91,f92,wcb,wcc,wc9,c12a,c12ab):
        Base(fn,rating,part,part2,material,size,self.evp.get(),self.evs.get(),a105,f22,f91,f92,wcb,wcc,wc9,c12a,c12ab)


root=Tk()
temp=gui(root)
root.mainloop()
